### ISSUE TITLE
Create Report

### ISSUE THREAD

**Issue by jullatt** [UniLuFS2020-ReplicationSeminar/23FS_DataM_ClassEx2_TrioMiners#3]
We now have some scripts to retrieve data, process it and then eventually perform some simple sentiment analysis on it. Everything now has to be merged into a report in an Rmarkdown file to give some sense to the analysis. Does somebody want to take on this task?

**Comment by nigi1992** [comment]
I'll do that.

**Comment by nigi1992** [comment]
done

**Comment by jullatt** [comment]
Thank you Nicolas, perfect!
